# Site settings
title: "Ryan Johnson"
email: brentryanjohnson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  &copy; Ryan Johnson, 2019.  Opinions are mine alone unless otherwise stated.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://brentryanjohnson.com" # the base hostname & protocol for your site
twitter_username: forestglenroad
github_username:  rentry

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge
include: ['_events']

# Pagination
plugins: [jekyll-paginate]
paginate: 5
paginate_path: posts/page:num/

# Minification
sass:
  style: compressed